/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for qat_rsapubkey
 */
#ifdef QAT_PKE_OLD_SUPPORTED
#include <linux/version.h>
#ifdef QAT_RSAPRIVKEY_ASN1_SUPPORT
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder qat_rsapubkey_decoder;

int qat_rsa_get_e(void *context, size_t hdrlen, unsigned char tag, const
		  void *value, size_t vlen);
int qat_rsa_get_n(void *context, size_t hdrlen, unsigned char tag, const
		  void *value, size_t vlen);
#endif
#endif
