########################################################################
#  SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0-only)
#  Copyright(c) 2016 - 2018, 2020 - 2021 Intel Corporation
########################################################################
# Kbuild file for out-of-tree driver only !!!DO NOT PUSH UPSTREAM!!!
include $(src)/Makefile
ccflags-$(ICP_HB_FAIL_SIM) += -DQAT_HB_FAIL_SIM=y
