########################################################################
#  SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0-only)
#  Copyright(c) 2018, 2020 Intel Corporation
########################################################################
ccflags-y := -I$(src)/../qat_common
obj-$(CONFIG_CRYPTO_DEV_QAT_4XXXVF) += qat_4xxxvf.o
qat_4xxxvf-objs := adf_drv.o adf_4xxxvf_hw_data.o
